version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: dev
  reviewers:
  - pwnorbitals
  ignore:
  - dependency-name: sweetalert2
    versions:
    - 10.13.1
    - 10.14.0
    - 10.14.1
    - 10.15.5
    - 10.15.6
    - 10.15.7
    - 10.16.0
  - dependency-name: http-proxy-middleware
    versions:
    - 1.0.6
    - 1.1.0
    - 1.1.1
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: marked
    versions:
    - 2.0.0
    - 2.0.1
  - dependency-name: vue-router
    versions:
    - 3.4.9
